version: '3'

services:
  ###> doctrine/doctrine-bundle ###

  ###< doctrine/doctrine-bundle ###
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_api
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database

###< symfony/mailer ###
